In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("D:\CC\SEM 3\COMP 258 Neural Networks\Assignments\Group Project\Student data.csv")

In [3]:
df.head()

First Term Gpa Second Term Gpa First Language  Funding  School  FastTrack  \
0              0               0              1        2       6          2   
1            2.5               2              3        4       6          1   
2           4.25        3.923077              1        1       6          2   
3       3.020833        2.321429              3        4       6          1   
4          4.275        4.326923              1        2       6          1   

   Coop  Residency  Gender Previous Education Age Group High School  \
0     1          1       2                  1         1          59   
1     2          2       2                  1         3           ?   
2     1          1       1                  2         3          92   
3     2          2       2                  2         3           ?   
4     1          1       1                  2         3          97   

  Math Score English Grade  FirstYearPersistence  
0         16             7                     1  
1          ?             7                     1  
2         41             9                     1  
3          ?             8                     1  
4          ?             9                     1

In [4]:
df.shape

(1437, 15)

In [5]:
df.describe()

Funding  School    FastTrack         Coop    Residency  \
count  1437.000000  1437.0  1437.000000  1437.000000  1437.000000   
mean      2.926931     6.0     1.741823     1.695198     1.406402   
std       1.257658     0.0     0.437784     0.460484     0.491332   
min       1.000000     6.0     1.000000     1.000000     1.000000   
25%       2.000000     6.0     1.000000     1.000000     1.000000   
50%       2.000000     6.0     2.000000     2.000000     1.000000   
75%       4.000000     6.0     2.000000     2.000000     2.000000   
max       9.000000     6.0     2.000000     2.000000     2.000000   

            Gender  FirstYearPersistence  
count  1437.000000           1437.000000  
mean      1.774530              0.791928  
std       0.419699              0.406070  
min       1.000000              0.000000  
25%       2.000000              1.000000  
50%       2.000000              1.000000  
75%       2.000000              1.000000  
max       3.000000              1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1437 entries, 0 to 1436
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   First Term Gpa        1437 non-null   object
 1   Second Term Gpa       1437 non-null   object
 2   First Language        1437 non-null   object
 3   Funding               1437 non-null   int64 
 4   School                1437 non-null   int64 
 5   FastTrack             1437 non-null   int64 
 6   Coop                  1437 non-null   int64 
 7   Residency             1437 non-null   int64 
 8   Gender                1437 non-null   int64 
 9   Previous Education    1437 non-null   object
 10  Age Group             1437 non-null   object
 11  High School           1437 non-null   object
 12  Math Score            1437 non-null   object
 13  English Grade         1437 non-null   object
 14  FirstYearPersistence  1437 non-null   int64 
dtypes: int64(7), object(8)
memory usage: 1

### Preprocessing

In [7]:
df.replace('?', np.nan, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1437 entries, 0 to 1436
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   First Term Gpa        1420 non-null   object
 1   Second Term Gpa       1277 non-null   object
 2   First Language        1326 non-null   object
 3   Funding               1437 non-null   int64 
 4   School                1437 non-null   int64 
 5   FastTrack             1437 non-null   int64 
 6   Coop                  1437 non-null   int64 
 7   Residency             1437 non-null   int64 
 8   Gender                1437 non-null   int64 
 9   Previous Education    1433 non-null   object
 10  Age Group             1433 non-null   object
 11  High School           694 non-null    object
 12  Math Score            975 non-null    object
 13  English Grade         1392 non-null   object
 14  FirstYearPersistence  1437 non-null   int64 
dtypes: int64(7), object(8)
memory usage: 1

In [9]:
X = df.iloc[:, :13]
y = df.iloc[:,14]

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
impute = SimpleImputer(missing_values=np.nan, strategy='mean', fill_value=None)

In [12]:
imputed_X = impute.fit_transform(X)

In [13]:
imputed_X

array([[ 0.        ,  0.        ,  1.        , ...,  1.        ,
        59.        , 16.        ],
       [ 2.5       ,  2.        ,  3.        , ...,  3.        ,
        77.15273775, 32.55794872],
       [ 4.25      ,  3.923077  ,  1.        , ...,  3.        ,
        92.        , 41.        ],
       ...,
       [ 2.020833  ,  2.45      ,  1.        , ...,  1.        ,
        78.        , 18.        ],
       [ 4.021739  ,  4.357143  ,  1.91101056, ...,  2.        ,
        77.15273775, 46.        ],
       [ 2.133333  ,  3.205882  ,  1.        , ...,  1.        ,
        81.        , 27.        ]])

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
scaled_X = scaler.fit_transform(imputed_X)

In [17]:
scaled_X

array([[-2.43730190e+00, -2.65171565e+00, -9.53603358e-01, ...,
        -1.14978963e+00, -2.16519662e+00, -1.87796704e+00],
       [-2.96367874e-01, -7.71183337e-01,  1.13990335e+00, ...,
         2.59661644e-01,  0.00000000e+00,  8.05882336e-16],
       [ 1.20228595e+00,  1.03702088e+00, -9.53603358e-01, ...,
         2.59661644e-01,  1.77093078e+00,  9.57479356e-01],
       ...,
       [-7.06713848e-01, -3.48063568e-01, -9.53603358e-01, ...,
        -1.14978963e+00,  1.01058550e-01, -1.65113133e+00],
       [ 1.00680925e+00,  1.44515845e+00, -2.32425935e-16, ...,
        -4.45063993e-01,  0.00000000e+00,  1.52456864e+00],
       [-6.10371817e-01,  3.62666694e-01, -9.53603358e-01, ...,
        -1.14978963e+00,  4.58888313e-01, -6.30370627e-01]])

### train test split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.2, random_state=42)

In [20]:
X_train, X_test, y_train, y_test

(array([[ 1.14594598e+00,  1.08584232e+00, -9.53603358e-01, ...,
          2.59661644e-01,  5.78164901e-01, -2.90117059e-01],
        [-5.37222952e-01, -4.24770677e-02, -9.53603358e-01, ...,
          1.66911292e+00, -1.92664344e+00, -1.53771347e+00],
        [-5.19770058e-01,  2.58631885e-01,  1.13990335e+00, ...,
         -1.14978963e+00,  5.78164901e-01,  6.17225788e-01],
        ...,
        [-2.25003691e-01,  4.25088887e-02,  1.13990335e+00, ...,
          2.59661644e-01,  0.00000000e+00,  8.05882336e-16],
        [ 4.61815711e-02,  4.53624006e-03, -9.53603358e-01, ...,
         -1.14978963e+00, -3.76047801e-01,  3.90390076e-01],
        [ 5.38596398e-01,  5.96476096e-01,  1.13990335e+00, ...,
          9.64387282e-01,  0.00000000e+00,  8.05882336e-16]]),
 array([[-5.70407430e-01, -1.17863169e+00, -9.53603358e-01, ...,
         -4.45063993e-01, -1.44953709e+00,  8.05882336e-16],
        [-4.84770068e-01, -8.52946061e-01, -9.53603358e-01, ...,
         -1.14978963e+00, -6.14600977e

### Model Creation

In [21]:
import tensorflow as tf

In [23]:
#hidden_layer_size = 9
model = tf.keras.Sequential([
    tf.keras.layers.Dense(9, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(4, activation='relu'),
    tf.keras.layers.Dense(2, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 9)                 126       
                                                                 
 dense_6 (Dense)             (None, 6)                 60        
                                                                 
 dense_7 (Dense)             (None, 4)                 28        
                                                                 
 dense_8 (Dense)             (None, 2)                 10        
                                                                 
 dense_9 (Dense)             (None, 1)                 3         
                                                                 
Total params: 227 (908.00 Byte)
Trainable params: 227 (908.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
